spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/hello_quartz?useUnicode=true
    username: root
    password: a@123456
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
    